### PR TITLE
Added a function that randomizes the memberlist on members page on re…

### PR DESCRIPTION
**Pull request by joshua125**
…load. Did this by replacing data.users in memberlist.js with my custom randomUserList function

## Issue, Bugfix or New Feature:
Related issue: [Link to related issue.](link)

## Description
Describe your changes here.
Created a function randomUserList that takes the user array in MemberList.js and shuffles it around each time react reloads the page. 
## Tasks
- [x] Feature 1 
- [x] Feature 2
- [ ] Feature 3

## :warning:  Warning :warning:
Write down warnings here.
I develop on a windows system..I'm not sure if that could cause issues with the yarn updating or editing the React config stuff...

### CODE REVIEW

**Comment by adamzev** [comment]
Hey Joshua,

Thanks for submitting the pull request! The reason you are seeing some repetition is that the return statement is inside of the for loop. So the shuffle function is only happening once rather than on the whole array.  Let the for loop finish before returning and you'll be golden. Also, if you could add a .gitignore for the node_modules folder, that'd be helpful. 

Thanks,

Adam

**Comment by joshua125** [comment]
Thanks for the feedback! I'll make the changes and resubmit.

**Comment by adamzev** [comment]
@joshua125 I don't think I've seen those changes. Let me know if you need any help. If you don't have time to finish this, that's fine too, I'll mark the task as up for grabs to complete this based on what you started. There have also been several commits since you worked on this so I'd recommend pulling them so there aren't any merge conflicts.

**Comment by joshua125** [comment]
Hey, lost track of it. I'll push the changes this evening once I get near
my rig.

Thanks for checking in.

**Pull request closed without merging**
